### ISSUE TITLE
ubuntu 下的ibus-rime, 好象无法复用"\"按键

### ISSUE THREAD

**Issue by YaoLiMuMu** [rimebrew/rime_latex#19]
1. 可以作为单独方案可以使用，在default.yaml的schema list加入latex就可以了。
2.  但是在ubuntu 下的ibus-rime, 测试了下，无法与其他方案混用， 好像因为无法复用"\"按键， 就算用recognizer/patterns/reverse_lookup: "^\\.+$"绑定了“\”键， 还是会先受到punctuator和symbols影响， 按下按键后， 先触发输入\符号， 无法用于配合做字典组成latex用词，

**Comment by shenlebantongying** [comment]
> 先受到punctuator和symbols影响， 按下按键后， 先触发输入\符号， 无法用于配合做字典组成latex用词，

那把原输入法的 `\` 删掉 :sweat_smile: ?

**Comment by YaoLiMuMu** [comment]
删掉后， \符号直接上屏了

**Comment by YaoLiMuMu** [comment]
总算解决了
```yaml
"engine/translators/@after last": script_translator@latex_input # 使用两个\\, 因为\\会被symbol识别自动上临时区, 所以相当于按了两次
  "recognizer/patterns/latex_input": "^\\\\.+$"
  latex_input:
    tag: latex_input
    dictionary: latex
    prefix: "\\"
    enable_completion: true
    tips: "Tex"
```
如代码要使用两个\\, 但是实际按键只需要一次\按键＋后续的latex符号就可以.
另外记得在记得在half_shape 和full_shape中加上"\\": ["\\"], 避免\按键后跳过翻译直接上屏.
