### ISSUE TITLE
是否能通过配置快捷键切换至其它输入方案

### ISSUE THREAD

**Issue by moncohoo** [rimebrew/rime_latex#28]
Windows 版本小狼毫，latex 为 standalone input method。我的配置是：

File: default.custom.yaml
```yaml
patch:
  "key_binder/bindings/+":
    - { when: always, accept: Control+Shift+F1, select: latex }
    - { when: always, accept: Control+Shift+F2, select: double_pinyin_flypy }

  schema_list:
    - schema: latex
    - schema: double_pinyin_flypy
```

这里我配置了快捷键想要快速切换输入模式，在 double_pinyin_flypy 模式下都能用快捷键切换至指定输入方案（比如切换至 latex 或它自身）；但是一旦在 latex 模式下，就不能通过快捷键切换至任何输入方案了。
通过快捷键切换至其它输入方案是非常省心的，尤其是使用很多个方案的场景，能够用肌肉记忆快速定位至指定的输入方案，不用打开「方案选单」一个个进行选择。大佬有什么解决方案吗？

**Comment by Iey4iej3** [comment]
这是 rime 本身的问题，和这个方案无关。去那里问更好。

**Comment by moncohoo** [comment]
明白了，既然只是在 latex 模式下不能切换，那问题多半出在 latex.schema.yaml。我对比了其它输入方案的配置，尝试了一下，只需在 engine/processors 下导入 key_binder，并配置快捷键就可以了。问题已经解决。

File: latex.schema.yaml
```yaml
# Rime schema
# encoding: utf-8


schema:
  schema_id: latex
  name: Latex Math Symbols
  version: "1.1"
  author:
    - slbtty <shenlebantongying@gmail.com>
    - mark <mark@mkmark.net>
  description: |
    Latex Math Symbols Input Method.
    You have to type '\' first to get symbols.
    This schema is intended to be used as an addon for other input methods.

engine:
  processors:
    - key_binder  # 导入 key_binder
    - speller     # to enable alphabet & initials below.
    - selector
    - navigator
    - express_editor
  segmentors:
    - abc_segmentor
    - fallback_segmentor
  translators:
    - table_translator

# 配置自己的快捷键。这里我只需要两个切换输入方案的快捷键，并且尽可能避免默认快捷键与 latex 输入方案的冲突，所以不从其他方案继承快捷键。
key_binder:
  bindings:
    - { when: always, accept: Control+Shift+F1, select: latex }
    - { when: always, accept: Control+Shift+F2, select: double_pinyin_flypy }
# # 否则，如果需要继承其它方案的快捷键，可以参考这段注释掉的配置替换 key_binder 的代码：
# key_binder:
#   import_preset: default  # 从 default.yaml 继承通用的
#   # bindings:             # 再增加方案专有的

speller:
  alphabet: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789\^_-><+-=()[]'
  initials: '\_^'
  auto_select: true

translator:
  dictionary: latex
  enable_sentence: false
  enable_user_dict: false

```
